### ISSUE TITLE
Show avatars next to users' names when chatting

### ISSUE THREAD

**Issue by Spidersouris** [RoseTheFlower/newsteamchat#1]
Is there a way to do so?

**Comment by RoseTheFlower** [comment]
The simplest way to do it without adjusting the spacing between the rest of the elements is to remove this part from friends.custom.css:

```
.ChatRoomSpeaker .speaker .speakerAvatar,
.ChatMsgSlashEmote .speaker .speakerAvatar, .speaker .speakerStatus{
opacity: 0!important;
width: 0.5px!important;}
```

The lack of avatars is intended though, so let me know if the above addresses your personal request.

**Comment by Spidersouris** [comment]
Thanks! It's working perfectly.
