### ISSUE TITLE
Is there a way to separate player name and status color ?

### ISSUE THREAD

**Issue by Yashirow** [RoseTheFlower/newsteamchat#13]
Hi, just want to know how to separate the player name and the status color/opacity. The theme in general is awesome but the only flaw for me is that game name/status is the same color and opacity than the player name. Is there a way to separate both ? Thanks.

**Comment by RoseTheFlower** [comment]
For those online, look for

`.online [class*="personanameandstatus_richPresenceLabel_"]`

For those in a game, look for

`color: inherit !important;`

and `.ingame[class*="personanameandstatus_twoLine_"]`

Set the color values to your preference, like
color: red or rgba(200,200,100,0.7)

**Comment by Yashirow** [comment]
Thanks a lot, exactly what I wanted.
