### ISSUE TITLE
White version?

### ISSUE THREAD

**Issue by c133** [RoseTheFlower/newsteamchat#2]
Hi RoseTheFlower,

I hope you are doing well. I recently used this software to skin my friends window on steam, it looks very nice. Is there any easy way to get a white version of the css instead of metro black? Would you or redsigma be willing to create a white theme?

Thank you.

**Comment by RoseTheFlower** [comment]
Thanks!
You can change most of the color values of the elements the same way you would [the accent color](https://github.com/RoseTheFlower/newsteamchat/wiki#accent-colors). For instance, clientBG is mainly responsible for the gray backgrounds, header_dark is for the black headers, and so forth.

**Comment by c133** [comment]
Hi Rose,

I've tried changing the background and some other of the css to colors that I wanted but it looks awful. Do you or anyone else have any plans to design a light version?

Thanks.

**Comment by RoseTheFlower** [comment]
I'll try to take further steps to make each element depend on a common variable because currently some are still defined separately. What's the source of the white version of Metro that you use and what's the full name?

**Comment by c133** [comment]
Hi Rose,

I actually dont use Metro but this skin instead:
https://github.com/airforsteam/Air-for-Steam

In that skin folder, specifically skins/Air-for-Steam-2019-0305/+Extras/Themes/Light is the light theme. It has white background and I like using purple accent with it. Of course I tried changing to white and purple in your friends.custom.css but it looked awful because I'm just manually changing stuff by itself. Also, I think the common variables for air skin are in Resource/styles/_vars.styles

I really appreciate your help :)

**Comment by c133** [comment]
https://i.imgur.com/Or9WIvG.png

This is what my friends used to look like before new UI ruined it, ignore the blue header. I was trying to get as close to this with friends.custom.css but failed

**Comment by RoseTheFlower** [comment]
I made some changes to point most of the colors at a variable. The settings window is a different story and would require further tweaking.
I also removed the black shadows that would affect a white theme.
You can try using [these](https://github.com/redsigma/UPMetroSkin/blob/master/Unofficial%204.3.1%20Patch/Extras/Themes/Metro%20White/Install/colors.styles#L298
) color values as a reference.
It should look less awful now, but I'll also keep the idea of a white theme in mind when making further updates.

**Comment by RoseTheFlower** [comment]
![image](https://user-images.githubusercontent.com/4759227/54874420-c3057680-4e0c-11e9-91bb-eed1558b80d3.png)

I changed nothing but the variables' values and I used the colors of Metro White for this. It's zero-effort but proof of lighter themes being a possibility now. Here are the values which aren't really to my liking but you can use them to produce something better.

> :root{
>   --focus: 0, 114, 198; /*default blue accent*/
>   --clientBG: 230,230,230;
>   --header_dark: 255,255,255;
>   --online: 93, 178, 255;
>   --ingame: 130, 186, 0;
>   --offline: 145, 145, 145;
>   --golden: 255, 255, 99;
>   --scrollbarSize: 15px;
>   --scrollbarBG: 0,0,0,.05;
>   --textentry: 207,207,207;
>   --white05: 0,0,0,.05;
>   --white50: 0,0,0,.5;
>   --white75: 0,0,0,.75;
>   --white: 0,0,0;
>   --border: 160,160,160;
>   --textentrybuttons: 160,160,160;
> }

**Comment by c133** [comment]
Hi Rose,

That looks amazing :) Thank you so much for spending time on this, I really appreciate it!!! <3 

I'm guessing there is no way to hide avatars by changing the code?

Please feel free to close this issue and I will be watching your repo for any future updates.

**Comment by RoseTheFlower** [comment]
You can add this to the code but with the avatars missing the other elements will move, resulting in changed padding. It's also adjustable but not as easily.

> .avatarHolder {
display:none!important;}

**Comment by c133** [comment]
![image](https://user-images.githubusercontent.com/5353882/54877456-bc630900-4de4-11e9-8c0d-408b67b23967.png)

Thanks Rose, I will try your recommended padding for the avatar removal soon.
I can't find where in the css the code is for controlling the color of the green text shown in the above pic, where it shows you how many people are left in the person's match that they are playing. Would you happen to know what this is called in the css / which line is controlling color for this so I can change it to purple?

**Comment by RoseTheFlower** [comment]
I made a change to the code so that it uses the **ingame** variable rather than the color specified by Valve. You can add the following to your code so you don't have to start over:

> .ingame.awayOrSnooze .personanameandstatus_richPresenceLabel_3Q6g1, .ingame .personanameandstatus_richPresenceLabel_3Q6g1, .ingame .personanameandstatus_richPresenceLabel_3Q6g1 a, .ingame .personanameandstatus_richPresenceLabel_3Q6g1 a:hover, .ingame .personanameandstatus_richPresenceLabel_3Q6g1 a:active, .ingame .personanameandstatus_richPresenceLabel_3Q6g1 a:visited{
color: rgba(var(--ingame), .5)!important;}

Thanks for pointing it out.

**Comment by c133** [comment]
![image](https://user-images.githubusercontent.com/5353882/54883208-0e2d8280-4e29-11e9-8b70-65a08b96e856.png)

Hi Rose, I added the padding code you suggested and it looks great, almost perfect. Currently each friend has 2 lines, their name and then their status either online or away. The final thing I would like to do is use CSS to hide the status so that each friend only takes up one line. I would then like 'online' friends to show up in black while 'away' friends are grey. Is this possible?

**Comment by RoseTheFlower** [comment]
You can add this to the code to hide the status line:

>.online .personanameandstatus_richPresenceLabel_3Q6g1, .online .personanameandstatus_gameName_qvibF.personanameandstatus_richPresenceLabel_3Q6g1 a, .online .personanameandstatus_gameName_qvibF.personanameandstatus_richPresenceLabel_3Q6g1 a:hover, .online .personanameandstatus_gameName_qvibF.personanameandstatus_richPresenceLabel_3Q6g1 a:active, .online .personanameandstatus_gameName_qvibF.personanameandstatus_richPresenceLabel_3Q6g1 a:visited {
    display: none !important;
}

Then again at the section where you adjust the padding you can decrease the height of each line (15 pixels in the example):

> .CompactFriendsList .friend, .CompactFriendsList .friendGroup .friend, .CompactFriendsList .friendGroup .SteamPlayerGroupFooter, .CompactFriendsList .friendGroup.gameGroup:not(.OtherGamesGroup) .friend {
    height: 15px !important;
}

Then add this to change the color of the users' names when they're away:

> .awayOrSnooze .personanameandstatus_playerName_1uxaf {
> color: rgb(160, 160, 160) !important;
}

As before, the color can be any RGB or hex value.

I'm not sure about the change in the color of the game title. You can try moving the extra code elsewhere. It might be a Valve issue as well. I currently have no way to test it because none of my friends' games have that line.

**Comment by c133** [comment]
Hi Rose,

When I add the code for decreasing height, it causes a lot of overlap between friends who have 3 lines (name, game, game status) vs friends who are just online and take up 1 line. Is there a way to add code and say only apply the height change to friends that are taking up 1 line?

**Comment by c133** [comment]
![image](https://user-images.githubusercontent.com/5353882/54892861-d6e6c200-4e78-11e9-8709-f18d86ceb088.png)

In other words, decrease height between the bottom users who aren't in-game but not the users above who are in-game

**Comment by c133** [comment]
Thank you.

**Comment by c133** [comment]
![image](https://user-images.githubusercontent.com/5353882/54893100-def33180-4e79-11e9-8313-cc6925a19e16.png)

Is there a way to reduce padding/height between bottom users in above pic but not the in-game users? Right now when I make any height changes there is overlap.

**Comment by RoseTheFlower** [comment]
I think the reason is that it overrides the other values. Here's the part that would define the height of the in-game lines:

> .CompactFriendsList .friend.ingame, .CompactFriendsList .friendGroup .friend.ingame {
>     height: 22px !important;
> }

Adjust the value to your liking.

**Comment by c133** [comment]
Sorry, I want to reduce space between friends who are online but not in-game. At the same time, I don't want to affect spacing of friends who are in-game

**Comment by c133** [comment]
![image](https://user-images.githubusercontent.com/5353882/54894679-83c53d00-4e81-11e9-839d-9cd79e974dd8.png)

Finally happy :) Thank you!

**Comment by RoseTheFlower** [comment]
> Another small thing I noticed is that in the image above you can see the first friend's game displays in bold while the 2nd friend playing the same game doesnt seem to be bold. This isn't really a big deal but I wonder if it has something to do with the order that I added CSS in.

Fixed this in the latest update.

**Comment by c133** [comment]
![image](https://user-images.githubusercontent.com/5353882/54934689-8f961b00-4ee4-11e9-86f5-10245ed6ece4.png)

I am really sorry to keep bothering you but do you know how I can fix this? In the pic you can see the 2nd in-game friend, there is a gap where the status line would otherwise be but for that particular game (R6) there will never be one of those lines

**Comment by RoseTheFlower** [comment]
I think the space is reserved for rich presence. It's how it is in the default skin. The reason the gap doesn't look as big in your other screenshots is the capital letters.

**Comment by RoseTheFlower** [comment]
I added the white theme values borrowed from Metro White to the CSS. There are still things to improve and test so I described it as experimental.
