### ISSUE TITLE
Favourited People Stretched.

### ISSUE THREAD

**Issue by SnowyHuskybutt** [RoseTheFlower/newsteamchat#3]
When you add someone into the favourite tabs, the icon itself and name get compressed and stretched pretty badly. I don't think it's meant to happen so if it could be fixed that'd be awesome!

**Comment by RoseTheFlower** [comment]
Just got to read this. The issue has been reported and [fixed](https://github.com/RoseTheFlower/newsteamchat/commit/014012eed2146941c4c657d2074fec1f4fc0181b) prior to your posting. Thanks for the feedback though!
