### ISSUE TITLE
Larger away icon at top right corner of avatar in favourites bar

### ISSUE THREAD

**Issue by CeezusCrisp** [RoseTheFlower/newsteamchat#4]
The "zzz" icon that appears when a person is away is almost impossible to see from how small it is. Would be nice if it was resized so that it's more visible.
![unknown(1)](https://user-images.githubusercontent.com/55898326/65802763-310d6a80-e1af-11e9-836f-f5a4ba400fba.png)

**Comment by RoseTheFlower** [comment]
Thanks for the feedback! I don't use the quick access feature so I rarely pay attention to it, which is also why it may feel different from the other elements.
I removed Valve's filter that made it darker. I can also increase the font size but I'm afraid of it breaking something in the future.
![image](https://user-images.githubusercontent.com/4759227/65815324-94ae8c80-e1dd-11e9-9036-33eb049afff0.png)

**Comment by CeezusCrisp** [comment]
Hey thanks for the fix. Would just like to add on if possible, in the original Steam chat UI, the profile avatars would dim but remain a blue line under them when the user goes away which was really useful for me to tell whether the person was still online. Thanks again anyways for the quick fix.
![unknown (1)](https://user-images.githubusercontent.com/55898326/65815975-cac52e00-e228-11e9-9296-76032bde709a.png)

**Comment by RoseTheFlower** [comment]
That was a design choice based on how the old Steam and old Metro skins handled the away status, and I feel like decreasing the avatar opacity negatively affects the overall "bright" look.
You can add the following lines to the .css file to achieve what you're looking for though!

```
.friend.quickAccessFriend.friend.awayOrSnooze {
    opacity: .5!important; }
```

**Comment by CeezusCrisp** [comment]
Is there a way for that to also apply when the user goes offline?
