### ISSUE TITLE
Font type

### ISSUE THREAD

**Issue by IR4TE** [RoseTheFlower/newsteamchat#5]
Hello is there a easy way to change the font in the new chat ui with this tool or is it possible to change it by myself in the .css file?

**Comment by PhantomGamers** [comment]
```
::-webkit-input-placeholder, body, input, select, textarea, .ChatMessageOpenGraph_Title, .ChatMessageOpenGraph_Body, .OpenGraphMessageURL_short
{
    font-family: "Fira Sans"!important;
}

.prettyprinted, .prettyprint {
    font-family: "Fira Code Retina"!important;
}
```

Bottom is for code blocks, top is for everything else. I think that's all inclusive, at least.

**Comment by RoseTheFlower** [comment]
You can also look for this line in the CSS:
`/*font-family: "Segoe UI", "Motiva Sans", Arial, Helvetica, sans-serif !important;*/`
Remove the /* and */ and replace the first font name with any other font if needed.

**Comment by IR4TE** [comment]
The line in CSS did work thank you very much. :D
