### ISSUE TITLE
import css url

### ISSUE THREAD

**Issue by camjac251** [RoseTheFlower/newsteamchat#7]
Check this out [2Retr0/Metr0ForSteam/master/resources/friends.custom.css](https://github.com/2Retr0/Metr0ForSteam/blob/master/resources/friends.custom.css)

They use a nice site that allows a raw file viewable from GitHub. This would be very useful for yours since you seem to be the only one who is actively updating.

You could have two files in the repo, `friends.custom.css` and `friends.custom.dev,css`. Dev would be the full CSS file and `friends.custom.css` could read out something like this
```css
@import url(https://raw.githack.com/RoseTheFlower/newsteamchat/master/friends.custom.dev.css);
```
That way with all new updates, it would always have the latest as its importing all the time. There are other users who use github pages as well to host their files like [github.com/The-HopelessGamer/Friends-UI-Custom](https://github.com/The-HopelessGamer/Friends-UI-Custom) which could be more secure if you don't trust githack.

**Comment by RoseTheFlower** [comment]
I've had it [as an option](https://github.com/RoseTheFlower/newsteamchat/wiki#automatic-updates) for over a year. I don't want to enforce it and risk breaking the skin for the users or expect them to trust me. I do create other tools that rely on trust but this is simple CSS and it doesn't have to at all.
