### ISSUE TITLE
Outline not lined up

### ISSUE THREAD

**Issue by lucaboox** [RoseTheFlower/newsteamchat#9]
https://i.imgur.com/SfoPBRA.png even after the update it still seems bugged dunno if you did not fix it or something.

**Comment by RoseTheFlower** [comment]
I can't really test for it without buying a border for my avatar.

I made a change that might or might not fix it.

**Comment by RoseTheFlower** [comment]
@PhantomGamers reported this as solved following my fix, so I will close the issue.

![image](https://user-images.githubusercontent.com/4759227/86523678-06141d80-be89-11ea-893b-c206174962bd.png)
